[pytest]
testpaths = tests
filterwarnings =
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated and scheduled for removal.*:DeprecationWarning:google\.protobuf\.internal\.well_known_types

norecursedirs =
    tests/archive
