from __future__ import annotations

import json
import shutil
import hashlib
from pathlib import Path
from typing import Any

from spine_ultrasound_ui.utils import ensure_dir, now_text
from spine_ultrasound_ui.runtime.model_bundle_contract import build_model_bundle_manifest, write_model_bundle_manifest


class ModelExportService:
    """Export training results into runtime-consumable model packages."""

    def export_segmentation_model(self, training_result: dict[str, Any], output_dir: Path, *, source_model_path: Path | None = None) -> dict[str, Any]:
        return self._export_package('lamina_seg', training_result, output_dir, source_model_path=source_model_path)

    def export_keypoint_model(self, training_result: dict[str, Any], output_dir: Path, *, source_model_path: Path | None = None) -> dict[str, Any]:
        return self._export_package('lamina_keypoint', training_result, output_dir, source_model_path=source_model_path)

    def export_ranking_model(self, training_result: dict[str, Any], output_dir: Path, *, source_model_path: Path | None = None) -> dict[str, Any]:
        return self._export_package('uca_rank', training_result, output_dir, source_model_path=source_model_path)

    def _export_package(
        self,
        model_name: str,
        training_result: dict[str, Any],
        output_dir: Path,
        *,
        source_model_path: Path | None = None,
    ) -> dict[str, Any]:
        """Export a model package with metadata and learned parameters.

        Args:
            model_name: Runtime model identifier.
            training_result: Trainer result payload.
            output_dir: Destination package directory.
            source_model_path: Optional external exported model such as ONNX.

        Returns:
            Package manifest containing runtime file paths.

        Raises:
            ValueError: Raised when ``training_result`` lacks learned parameters.
            FileNotFoundError: Raised when ``source_model_path`` is provided but
                does not exist.

        Boundary behaviour:
            Packages remain valid without external model binaries: the baseline
            learned parameters are saved into ``parameters.json`` and runtime
            adapters can execute using those statistics alone. Backend requests
            generated by MONAI/nnU-Net adapters are preserved in package metadata
            so operators can trace how the package should be refreshed later.
        """
        learned = dict(training_result.get('learned_parameters', {}))
        if not learned:
            raise ValueError('training_result.learned_parameters is required for export')
        package_dir = ensure_dir(Path(output_dir) / model_name)
        parameter_path = package_dir / 'parameters.json'
        meta_path = package_dir / 'model_meta.json'
        runtime_model_path = ''
        if source_model_path is not None:
            source_model_path = Path(source_model_path)
            if not source_model_path.exists():
                raise FileNotFoundError(source_model_path)
            runtime_model_path = source_model_path.name
            shutil.copy2(source_model_path, package_dir / source_model_path.name)
        parameter_path.write_text(json.dumps(learned, indent=2, ensure_ascii=False), encoding='utf-8')
        training_run_id = str(training_result.get('training_run_id', '') or self._training_run_id(model_name, training_result))
        dataset_source = str(training_result.get('dataset_source', '') or 'fixture')
        dataset_hash = str(training_result.get('dataset_hash', '') or self._stable_hash(dict(training_result.get('spec', {}))))
        release_state = str(training_result.get('release_state', '') or 'research_fixture')
        clinical_claim = str(training_result.get('clinical_claim', '') or 'non_clinical_research_only')
        benchmark_manifest_path = str(training_result.get('benchmark_manifest_path', '') or '')
        meta = {
            'generated_at': now_text(),
            'model_name': model_name,
            'package_name': f'{model_name}_fixture',
            'runtime_kind': 'deterministic_baseline',
            'release_state': release_state,
            'clinical_claim': clinical_claim,
            'training_run_id': training_run_id,
            'dataset_source': dataset_source,
            'dataset_hash': dataset_hash,
            'strict_runtime_required': True,
            'task_name': str(training_result.get('task_name', model_name) or model_name),
            'trainer_backend': str(training_result.get('trainer_backend', 'numpy_baseline') or 'numpy_baseline'),
            'training_spec': self._portable_payload(dict(training_result.get('spec', {}))),
            'runtime_model_path': runtime_model_path,
            'parameter_path': str(parameter_path.name),
            'metrics': dict(training_result.get('metrics', {})),
            'training_request_path': str(training_result.get('training_request_path', '') or ''),
            'dependency_status': dict(training_result.get('dependency_status', {})),
            'launch_plan': dict(training_result.get('launch_plan', {})),
            'benchmark_manifest_path': benchmark_manifest_path,
        }
        meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding='utf-8')
        manifest = build_model_bundle_manifest(
            bundle_id=f"{model_name}:{package_dir.name}",
            package_name=package_dir.name,
            runtime_profile='clinical_mainline',
            weights_path=runtime_model_path or str(parameter_path.name),
            entrypoint=f'spine_ultrasound_ui.training.runtime_adapters.{model_name}',
            parameter_path=str(parameter_path.name),
            meta_path=str(meta_path.name),
            metrics=dict(training_result.get('metrics', {})),
            training_run_id=training_run_id,
            dataset_source=dataset_source,
            dataset_hash=dataset_hash,
            trainer_backend=str(training_result.get('trainer_backend', 'numpy_baseline') or 'numpy_baseline'),
            release_state=release_state,
            clinical_claim=clinical_claim,
            benchmark_manifest_path=benchmark_manifest_path,
            strict_runtime_required=True,
        )
        manifest_path = write_model_bundle_manifest(package_dir, manifest)
        return {
            'package_dir': str(package_dir),
            'parameter_path': str(parameter_path),
            'model_meta_path': str(meta_path),
            'runtime_model_path': runtime_model_path,
            'bundle_manifest_path': str(manifest_path),
        }

    @staticmethod
    def _stable_hash(payload: dict[str, Any]) -> str:
        data = json.dumps(payload, ensure_ascii=False, sort_keys=True, default=str).encode('utf-8')
        return hashlib.sha256(data).hexdigest()

    def _training_run_id(self, model_name: str, training_result: dict[str, Any]) -> str:
        return f"{model_name}:{self._stable_hash({'model': model_name, 'metrics': training_result.get('metrics', {}), 'spec': training_result.get('spec', {})})[:16]}"

    @classmethod
    def _portable_payload(cls, payload: dict[str, Any]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in payload.items():
            if isinstance(value, Path):
                result[key] = cls._portable_path(value)
            elif isinstance(value, dict):
                result[key] = cls._portable_payload(value)
            elif isinstance(value, list):
                result[key] = [cls._portable_value(item) for item in value]
            else:
                result[key] = cls._portable_value(value)
        return result

    @classmethod
    def _portable_value(cls, value: Any) -> Any:
        if isinstance(value, Path):
            return cls._portable_path(value)
        if isinstance(value, str) and value.startswith('/'):
            return cls._portable_path(Path(value))
        if isinstance(value, dict):
            return cls._portable_payload(value)
        if isinstance(value, list):
            return [cls._portable_value(item) for item in value]
        return value

    @staticmethod
    def _portable_path(path: Path) -> str:
        repo_root = Path(__file__).resolve().parents[3]
        try:
            return str(path.resolve().relative_to(repo_root))
        except Exception:
            return path.name
