function(robot_core_apply_sdk_policy target_name)
  if(ROBOT_CORE_PROFILE STREQUAL "prod" AND NOT VendoredRokaeSdk_FOUND)
    message(FATAL_ERROR "ROBOT_CORE_PROFILE=prod requires an explicit xCore SDK toolchain. Vendored fallback is disabled.")
  endif()
  if(VendoredRokaeSdk_FOUND)
    target_link_libraries(${target_name} PRIVATE Rokae::xCoreSDK)
    if(ROBOT_CORE_WITH_XMATE_MODEL AND TARGET Rokae::xMateModel)
      target_link_libraries(${target_name} PRIVATE Rokae::xMateModel)
    endif()
  endif()
endfunction()
