from PySide6.QtWidgets import QFormLayout, QGridLayout, QGroupBox, QLabel, QTextEdit, QVBoxLayout, QWidget


class PreparePage(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.setSpacing(12)

        title = QLabel("系统准备")
        title.setObjectName("PageTitle")
        subtitle = QLabel("用于开机自检、硬件连通性确认、SDK 主线检查与当前运行模式核对。")
        subtitle.setObjectName("PageSubtitle")
        layout.addWidget(title)
        layout.addWidget(subtitle)

        grid = QGridLayout()
        grid.setSpacing(12)

        box_hw = QGroupBox("硬件与载荷")
        form_hw = QFormLayout(box_hw)
        self.lbl_toolset = QLabel("-")
        self.lbl_toolset.setObjectName("FieldValue")
        self.lbl_load = QLabel("-")
        self.lbl_load.setObjectName("FieldValue")
        self.lbl_sdk = QLabel("-")
        self.lbl_sdk.setObjectName("FieldValue")
        self.lbl_robot_class = QLabel("-")
        self.lbl_robot_class.setObjectName("FieldValue")
        form_hw.addRow("Toolset", self.lbl_toolset)
        form_hw.addRow("Load", self.lbl_load)
        form_hw.addRow("SDK", self.lbl_sdk)
        form_hw.addRow("Robot class", self.lbl_robot_class)
        grid.addWidget(box_hw, 0, 0)

        box_runtime = QGroupBox("运行状态")
        form_runtime = QFormLayout(box_runtime)
        self.lbl_power = QLabel("-")
        self.lbl_power.setObjectName("FieldValue")
        self.lbl_mode = QLabel("-")
        self.lbl_mode.setObjectName("FieldValue")
        self.lbl_rt_mode = QLabel("-")
        self.lbl_rt_mode.setObjectName("FieldValue")
        self.lbl_preferred_link = QLabel("-")
        self.lbl_preferred_link.setObjectName("FieldValue")
        form_runtime.addRow("Power", self.lbl_power)
        form_runtime.addRow("Operate mode", self.lbl_mode)
        form_runtime.addRow("RT mode", self.lbl_rt_mode)
        form_runtime.addRow("Link", self.lbl_preferred_link)
        grid.addWidget(box_runtime, 0, 1)

        box_io = QGroupBox("感知链路")
        form_io = QFormLayout(box_io)
        self.lbl_camera = QLabel("-")
        self.lbl_camera.setObjectName("FieldValue")
        self.lbl_ultrasound = QLabel("-")
        self.lbl_ultrasound.setObjectName("FieldValue")
        self.lbl_pressure = QLabel("-")
        self.lbl_pressure.setObjectName("FieldValue")
        self.lbl_ip_pair = QLabel("-")
        self.lbl_ip_pair.setObjectName("FieldValue")
        form_io.addRow("Camera", self.lbl_camera)
        form_io.addRow("Ultrasound", self.lbl_ultrasound)
        form_io.addRow("Pressure", self.lbl_pressure)
        form_io.addRow("Robot IP", self.lbl_ip_pair)
        grid.addWidget(box_io, 1, 0, 1, 2)

        layout.addLayout(grid)

        note = QLabel("进入自动扫查前，请确认 Power=ON、自动模式、生效链路为有线直连，且 Camera / Ultrasound / Pressure 三路均 fresh。")
        note.setObjectName("MutedLabel")
        note.setWordWrap(True)
        layout.addWidget(note)

        readiness_box = QGroupBox("启动前检查")
        readiness_layout = QVBoxLayout(readiness_box)
        self.lbl_readiness = QLabel("就绪度：0%")
        self.lbl_readiness.setObjectName("FieldValue")
        self.txt_blockers = QTextEdit()
        self.txt_blockers.setReadOnly(True)
        self.txt_blockers.setMinimumHeight(128)
        self.txt_blockers.setPlaceholderText("阻塞项、联锁和下一步建议将在这里显示。")
        readiness_layout.addWidget(self.lbl_readiness)
        readiness_layout.addWidget(self.txt_blockers)
        layout.addWidget(readiness_box)

        sdk_box = QGroupBox("SDK 对齐检查")
        sdk_layout = QVBoxLayout(sdk_box)
        self.lbl_sdk_state = QLabel("SDK 状态：-")
        self.lbl_sdk_state.setObjectName("FieldValue")
        self.txt_sdk = QTextEdit()
        self.txt_sdk.setReadOnly(True)
        self.txt_sdk.setMinimumHeight(136)
        self.txt_sdk.setPlaceholderText("机器人类、IP、链路、RT 模式和控制主线对齐情况将在这里显示。")
        sdk_layout.addWidget(self.lbl_sdk_state)
        sdk_layout.addWidget(self.txt_sdk)
        layout.addWidget(sdk_box)
        layout.addStretch(1)
