from PySide6.QtWidgets import QFormLayout, QGridLayout, QGroupBox, QLabel, QTextEdit, QVBoxLayout, QWidget


class RobotMonitorPage(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.setSpacing(12)

        title = QLabel("机器人监控")
        title.setObjectName("PageTitle")
        subtitle = QLabel("查看关节状态、TCP 姿态、笛卡尔力、控制器日志、RL 工程、路径库和 I/O 快照。")
        subtitle.setObjectName("PageSubtitle")
        layout.addWidget(title)
        layout.addWidget(subtitle)

        group = QGroupBox("机器人实时状态")
        form = QFormLayout(group)
        self.lbl_joint_pos = QLabel("-")
        self.lbl_joint_pos.setObjectName("FieldValue")
        self.lbl_joint_vel = QLabel("-")
        self.lbl_joint_vel.setObjectName("FieldValue")
        self.lbl_joint_torque = QLabel("-")
        self.lbl_joint_torque.setObjectName("FieldValue")
        self.lbl_tcp = QLabel("-")
        self.lbl_tcp.setObjectName("FieldValue")
        self.lbl_tcp.setWordWrap(True)
        self.lbl_cart_force = QLabel("-")
        self.lbl_cart_force.setObjectName("FieldValue")
        self.lbl_operate_mode = QLabel("-")
        self.lbl_operate_mode.setObjectName("FieldValue")
        self.lbl_power_state = QLabel("-")
        self.lbl_power_state.setObjectName("FieldValue")
        self.lbl_rl_state = QLabel("-")
        self.lbl_rl_state.setObjectName("FieldValue")
        self.lbl_drag = QLabel("-")
        self.lbl_drag.setObjectName("FieldValue")
        form.addRow("Joint Pos", self.lbl_joint_pos)
        form.addRow("Joint Vel", self.lbl_joint_vel)
        form.addRow("Joint Torque", self.lbl_joint_torque)
        form.addRow("TCP Pose", self.lbl_tcp)
        form.addRow("Cartesian Force", self.lbl_cart_force)
        form.addRow("Operate Mode", self.lbl_operate_mode)
        form.addRow("Power", self.lbl_power_state)
        form.addRow("RL", self.lbl_rl_state)
        form.addRow("Drag", self.lbl_drag)
        layout.addWidget(group)

        grid = QGridLayout()
        grid.setSpacing(12)

        log_box = QGroupBox("控制器日志")
        log_layout = QVBoxLayout(log_box)
        self.log_view = QTextEdit()
        self.log_view.setReadOnly(True)
        self.log_view.setPlaceholderText("控制器日志 / 事件流")
        log_layout.addWidget(self.log_view)
        grid.addWidget(log_box, 0, 0)

        io_box = QGroupBox("I/O 与路径资产")
        io_layout = QVBoxLayout(io_box)
        self.asset_view = QTextEdit()
        self.asset_view.setReadOnly(True)
        self.asset_view.setPlaceholderText("路径库、I/O 快照、xPanel 供电状态将在这里显示。")
        io_layout.addWidget(self.asset_view)
        grid.addWidget(io_box, 0, 1)

        layout.addLayout(grid)
